name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    env:
      GOVUK_ROOT_DIR: ${{ github.workspace }}
      GOVUK_HTTPS_CHECKOUT: 1
      TERM: dumb
      SKIP_BRANCH_CHECKS: 1
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker CLI
      uses: docker/setup-buildx-action@v3
    - name: Setup govuk-docker
      run: |
        # eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        git clone -b allow-https-checkout https://github.com/alphagov/govuk-docker.git
        # echo ${GITHUB_WORKSPACE}/govuk-docker/exe >> $GITHUB_PATH
        # cd govuk-docker
        # bin/setup || true
        # sudo --preserve-env=HOME env "PATH=$PATH" brew services restart dnsmasq
        sudo echo "$(cat ./hostnames.txt)" | sudo tee -a /etc/hosts
    - name: Create containers
      run: |
        cd govuk-docker
        make whitehall
        make government-frontend
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
